apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transaction-service.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
