apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transaction-service.fullname" . }}-pvc
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
